"""Add RegionDataORM and CountyDataORM

Revision ID: 844d0b34815e
Revises: 
Create Date: 2025-07-23 10:38:57.721724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844d0b34815e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('county_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('total_business_value', sa.Integer(), nullable=True),
    sa.Column('total_liquidation_value', sa.Integer(), nullable=True),
    sa.Column('total_creditor_return', sa.Integer(), nullable=True),
    sa.Column('total_working_capital_needs', sa.Integer(), nullable=True),
    sa.Column('total_pre_tax_profit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('county'),
    schema='fastapi_schema'
    )
    op.create_index(op.f('ix_fastapi_schema_county_data_id'), 'county_data', ['id'], unique=False, schema='fastapi_schema')
    op.create_table('region_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('total_business_value', sa.Integer(), nullable=True),
    sa.Column('total_liquidation_value', sa.Integer(), nullable=True),
    sa.Column('total_creditor_return', sa.Integer(), nullable=True),
    sa.Column('total_working_capital_needs', sa.Integer(), nullable=True),
    sa.Column('total_pre_tax_profit', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region'),
    schema='fastapi_schema'
    )
    op.create_index(op.f('ix_fastapi_schema_region_data_id'), 'region_data', ['id'], unique=False, schema='fastapi_schema')
    op.drop_index('ix_common_info_county_id', table_name='common_info_county', schema='fastapi_schema')
    op.create_index(op.f('ix_fastapi_schema_common_info_county_id'), 'common_info_county', ['id'], unique=False, schema='fastapi_schema')
    op.drop_index('ix_common_info_industry_id', table_name='common_info_industry', schema='fastapi_schema')
    op.create_index(op.f('ix_fastapi_schema_common_info_industry_id'), 'common_info_industry', ['id'], unique=False, schema='fastapi_schema')
    op.drop_index('ix_common_info_region_id', table_name='common_info_region', schema='fastapi_schema')
    op.create_index(op.f('ix_fastapi_schema_common_info_region_id'), 'common_info_region', ['id'], unique=False, schema='fastapi_schema')
    op.drop_index('ix_company_data_id', table_name='company_data', schema='fastapi_schema')
    op.create_index(op.f('ix_fastapi_schema_company_data_id'), 'company_data', ['id'], unique=False, schema='fastapi_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_schema_company_data_id'), table_name='company_data', schema='fastapi_schema')
    op.create_index('ix_company_data_id', 'company_data', ['id'], unique=False, schema='fastapi_schema')
    op.drop_index(op.f('ix_fastapi_schema_common_info_region_id'), table_name='common_info_region', schema='fastapi_schema')
    op.create_index('ix_common_info_region_id', 'common_info_region', ['id'], unique=False, schema='fastapi_schema')
    op.drop_index(op.f('ix_fastapi_schema_common_info_industry_id'), table_name='common_info_industry', schema='fastapi_schema')
    op.create_index('ix_common_info_industry_id', 'common_info_industry', ['id'], unique=False, schema='fastapi_schema')
    op.drop_index(op.f('ix_fastapi_schema_common_info_county_id'), table_name='common_info_county', schema='fastapi_schema')
    op.create_index('ix_common_info_county_id', 'common_info_county', ['id'], unique=False, schema='fastapi_schema')
    op.drop_index(op.f('ix_fastapi_schema_region_data_id'), table_name='region_data', schema='fastapi_schema')
    op.drop_table('region_data', schema='fastapi_schema')
    op.drop_index(op.f('ix_fastapi_schema_county_data_id'), table_name='county_data', schema='fastapi_schema')
    op.drop_table('county_data', schema='fastapi_schema')
    # ### end Alembic commands ###
